server:
  port: 443
    # http: 80


spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: oauth2-service
          uri: https://oauth2-service:8080
          predicates:
            - Path=/oauth2/**

        - id: user-service
          uri: https://user-service:8080
          predicates:
            - Path=/user/**, /file/**
#          filters:
#            - RewritePath=/oauth/(?<path>.*),/$\{path}

        - id: matcing-service
          uri: https://user-service:8080
          predicates:
            - Path=/matcing/**

        - id: notify-service
          uri: https://user-service:8080
          predicates:
            - Path=/notify/**
#          filters:
#            - RewritePath=/oauth/(?<path>.*),/$\{path}


        - id: react-framework
          uri: https://react-framework:3000/
          predicates:
            - Path=/playground/**
#          filters:
#            - RewritePath=/pages/(?<path>.*),/$\{path}





  data:
    redis:
      host: redis
      port: 6379

oauth2:
  client:
    registration:
      client-id:
        kakao: 79c6d214ca859ea2806d6bd426ffb1fe

#eureka:
#  client:
#    fetch-registry: true # 유레카 클라이언트 활성화
#    register-with-eureka: true # 유레카 클라이언트 활성화
#    service-url:
#      defaultZone: http://localhost:8761/eureka # 유레카 클라이언트로 등록